name: dnase-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pysam
  - pybigwig
  - pyfaidx
  - samtools
  - bedtools
  - ucsc-bedgraphtobigwig
  - requests